name: Run PHP Script

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL of the Twitter video"
        required: true
        type: string

jobs:
  run-php-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Use the desired PHP version

      - name: Run PHP Script
        run: |
          php process.php "${{ github.event.inputs.video_url }}"
