name: Download Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the Twitter video'
        required: true
        default: ''

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp ffmpeg

      - name: Download Twitter Video
        run: |
          video_url="${{ github.event.inputs.video_url }}"
          yt-dlp $video_url -o "twitter_video.mp4"

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        with:
          name: twitter_video
          path: twitter_video.mp4
