name: Download Twitter Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL of the Twitter video to download"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Twitter Video
        run: |
          video_url="${{ github.event.inputs.video_url }}"
          youtube-dl $video_url -o "twitter_video.mp4"
          echo "::set-output name=download_url::https://<GITHUB_REPO_RAW_URL>/twitter_video.mp4"

      - name: Upload Video to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: twitter_video.mp4
          path: twitter_video.mp4
