name: Download Twitter Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Twitter Video URL'
        required: true
        default: 'https://twitter.com/user/status/1850681152429772842'

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install -U yt-dlp

      - name: Download Video
        run: |
          video_url="${{ github.event.inputs.video_url }}"
          yt-dlp "$video_url" -o "twitter_video.mp4"

      - name: Upload Video
        uses: actions/upload-artifact@v3
        with:
          name: twitter_video
          path: twitter_video.mp4
